environment:
  global:
    # Used by setup.py to use trace when compiling cython for coverage stats
    CYTHON_COVERAGE: 1

  matrix:
    - PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "32"
      ARCH: "x86"
      platform: "x86"
    - PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "32"
      ARCH: "x86"
      platform: "x86"
    - PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"
      ARCH: "amd64"
      platform: "x64"
    - PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      ARCH: "amd64"
      platform: "x64"

install:
  - "C:\Python38\scripts\pip install -r requirements.txt"
  - "C:\Python38\scripts\pip install twine codecov"
  - "C:\Python38\python setup.py build_ext -i --compiler=mingw32"

# Not a .NET project, we build in the install step instead
build: false

test_script:
  - C:\Python38\scripts\pytest winpty --cov=winpty -v"
  - C:\Python38\scripts\coveralls"
  - C:\Python38\scripts\codecov"

on_success:
  - powershell appveyor/publish.ps1"

# on_finish:
  # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
